### PR TITLE
fix(docs): grammatical mistakes

### PR DESCRIPTION
**Pull request by xNickyDev**
an user -> **a user**
a emoji -> **an emoji**
a invite -> **an invite**

### CODE REVIEW

**Comment by Natasquare** [comment]
did you seriously... committed once for every single file??

**Comment by xNickyDev** [comment]
obviously

**Comment by tiudvek** [comment]
actually im pretty sure its supposed to be
an user
an emoji
an invite

**Comment by Natasquare** [comment]
nah it's `a user`, because /yoo͞′zər/

**Comment by tiudvek** [comment]
wait what

**Comment by EnterausernameUwU** [comment]
Bro does not know grammar 😭🙏

**Comment by tiudvek** [comment]
> Bro does not know grammar 😭🙏

I REFUSE to believe someone who uses that string of emojis uses better grammar than me. I completely and utterly refuse to believe it.

**Comment by paratmr** [comment]
Forgescript hater: https://www.youtube.com/watch?v=xvFZjo5PgG0

**Comment by tiudvek** [comment]
> Forgescript hater: https://www.youtube.com/watch?v=xvFZjo5PgG0

Rickroll. Too bad I memorized all the links. Also, I see no reason pointing to me hating your AOI.JS copycat.

**Comment by paratmr** [comment]
> > Forgescript hater: https://www.youtube.com/watch?v=xvFZjo5PgG0
> 
> Rickroll. Too bad I memorized all the links. Also, I see no reason pointing to me hating your AOI.JS copycat.

Whooa memorized keklaugh lmfao kiddo. i just put "forgescript hater" to fool you and got triggered

**Comment by tiudvek** [comment]
> > > Forgescript hater: https://www.youtube.com/watch?v=xvFZjo5PgG0
> > 
> > 
> > Rickroll. Too bad I memorized all the links. Also, I see no reason pointing to me hating your AOI.JS copycat.
> 
> Whooa memorized keklaugh lmfao kiddo. i just put "forgescript hater" to fool you and got triggered

Yes, yes. I very much got triggered by your attempt to "fool" me. You are the first person to say "keklaugh," which just goes to show how you are on Discord every day, all 365 days of the year. Well, you could also be an 11 year old.

**Comment by paratmr** [comment]
Aint no way keklaugh, my bro really said "You are the first person to say "keklaugh," which just goes to show how you are on Discord every day, all 365 days of the year. Well, you could also be an 11 year old." ill bet you live in your moms basement kekw

**Comment by paratmr** [comment]
> > > > Forgescript hater: https://www.youtube.com/watch?v=xvFZjo5PgG0
> > > 
> > > 
> > > Rickroll. Too bad I memorized all the links. Also, I see no reason pointing to me hating your AOI.JS copycat.
> > 
> > 
> > Whooa memorized keklaugh lmfao kiddo. i just put "forgescript hater" to fool you and got triggered
> 
> Yes, yes. I very much got triggered by your attempt to "fool" me. You are the first person to say "keklaugh," which just goes to show how you are on Discord every day, all 365 days of the year. Well, you could also be an 11 year old.

Aint no way keklaugh, my bro really said "You are the first person to say "keklaugh," which just goes to show how you are on Discord every day, all 365 days of the year. Well, you could also be an 11 year old." ill bet you live in your moms basement kekw

**Comment by tiudvek** [comment]
Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on," - Linus Torvalds.

**Comment by tiudvek** [comment]
By the way, your grammar is all wrong. Please go back to preschool.

**Comment by yuminanase** [comment]
Stop arguing here and go to your dms.

**Comment by tiudvek** [comment]
There are no dms on GitHub. This isn't Discord, Yumi. You're even worse than him.

**Comment by yuminanase** [comment]
> There are no dms on GitHub. This isn't Discord, Yumi. You're even worse than him.

There is. I made it. But it's not for you.

**Comment by tiudvek** [comment]
Please just stop speaking. You're annoying.

**Comment by yuminanase** [comment]
Thank you

**Comment by paratmr** [comment]
> Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on," - Linus Torvalds.

Actually, "I have life" who am to talking? ghost? "and i speak to girls" who asked. Living in mom's basement is really sad kekw

**Comment by paratmr** [comment]
Btw, Looking at your profile/repositories, it makes me sad xD 🤣🤣

**Comment by tiudvek** [comment]
> > Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on," - Linus Torvalds.
> 
> Actually, "I have life" who am to talking? ghost? "and i speak to girls" who asked. Living in mom's basement is really sad kekw

Fix your English, and then you can speak to me.

**Comment by paratmr** [comment]
> > > Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on," - Linus Torvalds.
> > 
> > 
> > Actually, "I have life" who am to talking? ghost? "and i speak to girls" who asked. Living in mom's basement is really sad kekw
> 
> Fix your English, and then you can speak to me.

it's already fixed whahahah "Nerd | Programmer | Uses arch btw | Soda cracker addict yes, this is defense3 on discord" xD

**Comment by Iconicyansh** [comment]
Guys aren't gonna stop 💀 lmao

**Comment by Natasquare** [comment]
inb4 lock

**Comment by tiudvek** [comment]
> > > > Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on," - Linus Torvalds.
> > > 
> > > 
> > > Actually, "I have life" who am to talking? ghost? "and i speak to girls" who asked. Living in mom's basement is really sad kekw
> > 
> > 
> > Fix your English, and then you can speak to me.
> 
> it's already fixed whahahah "Nerd | Programmer | Uses arch btw | Soda cracker addict yes, this is defense3 on discord" xD

You feel the need to check profiles?

**Comment by tiudvek** [comment]
There is one last thing I have to say: If you have 2 REPOS, where one of them is BDFD, and the other is VENDETTA, you can not be talking. Guten nacht.

**Comment by Berk404** [comment]
Can you guys kindly stay quiet if you aren't going to comment something actually useful rather than a Twitter argument?

> "Actually, I have a life and I speak to girls. You, on the other hand are busy in your aoijs cult. "I'm surprised your alive because I don't think your smart enough to find a ... to suck on,"""

*Proceeds to waste his time arguing with random internet users*

**Comment by Sp3c1al0** [comment]
shut UP

**Comment by LordexDuck3990** [comment]
skibidi toilets took current pull request and yall now unable to do anything with it

**Comment by KizzayBunnyDev** [comment]
Berk can't edit this.

**Comment by KizzayBunnyDev** [comment]
Skidviady Toi toi yes yes

**Comment by KizzayBunnyDev** [comment]
Minebarteksa: seeing that they have copied your application, we will sue them for copies, long live the skdifivies toiketds

**Comment by KizzayBunnyDev** [comment]
Delete Forgescript NOW NOW DELETE FORGESCRIPT SKIDVIADY SKDIFIVA TOIKET TOKIET YES YES YES akdkqoqpworigjcjxnskk{~{`{•×^™{{|[₡©[{😄😭😁🤣🤣😀😭😀😭😃🤣😄🤣😙🤣🥲😏😋🥴😛🥴😶🥴😜🥴😤😑🤨😠😠🤒💩🤡💩👿💩😈💩🌛🎃👽🌞👾🌝👊🖖👋🤟🖐️🤟👐🤜👂🤜👃🦾👍🦾👅🦾🤰👩‍❤️‍💋‍👩🤰🐶🐨🐶🐨🐺🐨🌘🐵🌗🐵🌍🌓🌌🌓🌎🌘🍒🫐🍈🫐🍐🫐🥝🫐🍎🥭🍈🥭🍈🥭🍑🍑🍑🍑🍑🍑🍑🍉🍑🍑🍑🍑🍑🥕🥦🫐🍈🫐🍓🍋🍇🫐🥮🍰🍫🍰🍦🍰🥟🍘🍱🍘🥮🍯🍯🛼🏹🩰🏹🛹🥌🛹🥌🥍🛷🏸🛷 LMAOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by LordexDuck3990** [comment]
indeed but you should stop 🛑☝️

**Comment by KizzayBunnyDev** [comment]
👍

**Comment by KizzayBunnyDev** [comment]
bro wait, what the he-

**Comment by KizzayBunnyDev** [comment]
I didn't say that about, I'm a cute femboy " 💀

**Comment by tiudvek** [comment]
Holy shit shut the fuck up already were done fighting

**Comment by LordexDuck3990** [comment]
still skibidi toilets took this issue

**Comment by xNickyDev** [comment]
Wtf happened to my PR 👁️👄👁️

**Comment by tiudvek** [comment]
Berk you are very much right ;)

**Comment by Sp3c1al0** [comment]
Shut up skdipdi fans, i rule your moms 😈🔪 forgescript ahh haters while you a member, check your family. I boomed them

**Comment by LordexDuck3990** [comment]
no one asked, i already stole your cookies

**Comment by Sp3c1al0** [comment]
Ans i steak your weeeeweeee 😎

**Comment by Sp3c1al0** [comment]
Omg i cant spell

**Comment by Sp3c1al0** [comment]
I will steal everything u have

**Comment by DodoGames7** [comment]
> Omg i cant spell

is that why Grammarly has been created? dang

**Comment by EnterausernameUwU** [comment]
> > Omg i cant spell
> 
> is that why Grammarly has been created? dang

That is not really a good comeback

**Comment by LordexDuck3990** [comment]
bro not my weewee thats crazy and rude asf 😭🥺😢

**Comment by Sp3c1al0** [comment]
Shut up omg annoying a- s- w- t- GOSH ENOUGH! let me say anything u scared kid

**Comment by EnterausernameUwU** [comment]
> bro not my weewee thats crazy and rude asf 😭🥺😢

I'm going to touch you





🍴

**Comment by LordexDuck3990** [comment]
> > bro not my weewee thats crazy and rude asf 😭🥺😢
> 
> I'm going to touch you
> 
> 
> 
> 
> 
> 🍴

eww

**Comment by EnterausernameUwU** [comment]
> Shut up omg annoying a- s- w- t- GOSH ENOUGH! let me say anything u scared kid

I'm touching you too

**Comment by DodoGames7** [comment]
> > is that why Grammarly has been created? dang
> That is not really a good comeback

uhm, you got a point here, i think i probably should have did the copy pasta of Grammarly instead, here goes my internet social credit being gone

**Comment by EnterausernameUwU** [comment]
> > > bro not my weewee thats crazy and rude asf 😭🥺😢
> > 
> > 
> > I'm going to touch you
> > 🍴
> 
> eww

Baby girl

**Comment by Sp3c1al0** [comment]
> > Shut up omg annoying a- s- w- t- GOSH ENOUGH! let me say anything u scared kid
> 
> I'm touching you too

Im gonna touch your meat and make them a hotdog

**Comment by EnterausernameUwU** [comment]
> > > Shut up omg annoying a- s- w- t- GOSH ENOUGH! let me say anything u scared kid
> > 
> > 
> > I'm touching you too
> 
> Im gonna touch your meat and make them a hotdog

Do it baby girl

**Comment by Sp3c1al0** [comment]
Shut up yout meat too small

**Comment by Sp3c1al0** [comment]
Gosh i cabt sprell

**Comment by EnterausernameUwU** [comment]
> Shut up yout meat too small

🙈

**Comment by Sp3c1al0** [comment]
Your monki? Good

**Comment by LordexDuck3990** [comment]
i weight that much only because of my meat 😔🥓

**Comment by Sp3c1al0** [comment]
Your meat tastes good, gonna make it a big hotdog as its big size

**Comment by LordexDuck3990** [comment]
stop now

**Comment by Sp3c1al0** [comment]
No kiddo, im gonna kiss yout meat snd s*ck it.

**Comment by EnterausernameUwU** [comment]
> No kiddo, im gonna kiss yout meat snd s*ck it.

Why not me :(

**Comment by DevChr0me** [comment]
hI guYs I AM nEW HErE :D

**Comment by DevChr0me** [comment]
¿Somebody is here?, I am alone :(

**Comment by DevChr0me** [comment]
real

**Comment by DevChr0me** [comment]
I'M goING bYE

**Comment by DevChr0me** [comment]
Next Update: added $createApplicationCommand
$allGuildsNames
$allGuildsInviteCreate


Berk once said: mi primeeera chamba!?!!!!!?

**Comment by DevChr0me** [comment]
My imagination is evolving

**Pull request merged**
