### PR TITLE
Added Functions

### PR DESCRIPTION
**Pull request by Cyberghxst**
- $cwd: Returns the process cwd.
- $import: Import a property from the provided file.
- $pathJoin: Join the given file paths.
- $readdir: Reads a directory and load the result into an environment variable.

Fixed
- Import in properties/embed.ts

### CODE REVIEW

**Comment by Cyberghxst** [comment]
Also, I ran the docgen command.

**Comment by YuzuTheNeko** [comment]
fix conflicts again pls

**Comment by Xloxn4050** [comment]
e

**Comment by Xloxn4050** [comment]
MOM IM FAMOUS

**Pull request closed without merging**
